### ISSUE TITLE
/home/sliceruser/run.sh: line 20: exec: jupyter-labhub: not found 

### ISSUE THREAD

**Issue by dazzag24** [Slicer/SlicerDocker#43]
When run on a jupyterhub system as an additional user profile choice:

```
singleuser:
  profileList:
    - display_name: "Default"
      description: "A standard JupyterLab setup"
      default: True
    - display_name: "JupyterLab with Slicer"
      description: "A  modified JupyterLab with 3DSlicer"
      kubespawner_override:
        image: slicer/slicer-notebook
```
   

the docker image fails to start with this error:

```
+++ dirname /home/sliceruser/run.sh
++ cd /home/sliceruser
++ pwd
+ script_dir=/home/sliceruser
+ source /home/sliceruser/start-xorg.sh
++ set -e
++ set +x
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
 
X.Org X Server 1.20.8
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.19.0-8-amd64 x86_64 Debian
Current Operating System: Linux jupyter-xxxxx 4.14.225-169.362.amzn2.x86_64 #1 SMP Mon Mar 22 20:14:50 UTC 2021 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.14.225-169.362.amzn2.x86_64 root=UUID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ro console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 nvme_core.io_timeout=4294967295 rd.emergency=poweroff rd.shell=0
Build Date: 31 March 2020  10:14:40AM
xorg-server 2:1.20.8-2 (https://www.debian.org/support) 
Current version of pixman: 0.36.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "./10.log", Time: Thu Oct  7 11:11:47 2021
(++) Using config file: "/home/sliceruser/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/home/sliceruser/run.sh: line 20: exec: jupyter-labhub: not found
```

Any pointers?

Thanks
